#!/usr/bin/ruby
glue = ARGV[0] || ""
flag = ARGV[1] || ""

males = %w[aki akihiko akihiro akio akira akito aoi atsushi bishamon bokusui chitose chokichi dai daichi daigoro daijiro daiki daisaku daishiro daisuke daisuke daitaro den dengyo denji denjiro eiichi eiji eikichi fumio gen gendo genji genjiro genkei genkichi genku genmei ginjiro gohachiro gokomatsu goro hachiro hachiuma hajime hama haru harujiro haruka haruo heiji hideaki hideki hidenobu hideo hikaru hiro hiroaki hiroki hiromasa hiroshi hiroyuki hisao hisashi hisayuki hisoka hitoshi hiyoshi hoshu hotaka ichiro ietaka isamu isao ishio isoroku iwao izanagi jiro jo joji jun junichi jurou kaede kaito kamenosuke kanji katashi katsu katsumi katsuo katsutoshi kazu kazuhiko kazuhiro kazuki kazuo kei keiichi keiji ken kenichi kenji kenshin kenta kenzo kichirou kin kinjiro kioshi kiosho kita kiyoshi ko kobo kohaku koichi koji kojiro koki kou kouhei kouji koujiro kumakichi kunihiko kunio kurou kyo kyou madoka makoto mamoru mamosuke manabu masa masaaki masahiko masahiro masajun masaki masanori masao masaru masashi masato masayoshi masayuki masumi michi michio mikio minori minoru mitsuo mitsuru nagataka nao naoki naoko noboru nobu nobuo nobuyuki nori norimasa norio ogano orochi osamu ozuru raiden ren rikio riku ringo rokuro ryo ryota ryouichi ryouta ryu ryunosuke saburo sadao samuru satoru satoshi seichi seiichi seiji sen shichiro shigeo shigeru shin shinakio shinichi shinji shinjiro shinshiro shiro sho shoichi shoji shou shouhei shouji shuichi shuji shunshi shunsuke shunsuke shuntaro shuzo sora sota souta susumu tadao tadashi tahara taizo takahiro takao takashi takayuki takehiko takehiro takeo takeshi takumi takuya tamotsu tani taro tasou tatsuo tatsuru tatsuya teruo tetsuo tetsuya tobikuma tokujiro tokutaro tomi tomio torao toru toshi toshiaki toshihiro toshio toshiyuki toyohisa tsubasa tsuneo tsutomu tsuyoshi umi yasahiro yaso yasuhiro yasunari yasuo yasushi yemon yoichi yokichi yori yoshi yoshiaki yoshihara yoshihiro yoshihisa yoshikazu yoshinari yoshinori yoshio yoshiro yoshito yoshiyuki youji yu yudai yuichi yuji yuki yukio yusuke yuta yutaka yuto zen zenjiro zenshiro zentaro zuisho]

females = %w[ai aika aiko aimi akane akemi aki akiko amaterasu aoi arisu asako asami asuka atsuko avaron aya ayaka ayako ayame ayano ayumi azumi chiaki chiasa chie chieko chiharu chika chikako chinatsu chiyo chiyoko chou eiko emi emiko eri etsuko fuji fumiko hana hanako haru haruka haruki haruko harumi hideko hikari hikaru hiro hiroko hiromi hisako hisoka hitomi hoshi hotaru izanami izumi jun junko kaede kanae kaori kaoru kasumi katsumi kayo kazue kazuko kazumi kei keiko kiku kimi kimie kimiko kin kiyoko kiyomi ko kohaku konoha kotomi kotone kou kumiko kyo kyoko kyou madoka mai maiko maki makiko makoto mana manaka manami mari mariko marisa masa masako masami masumi masuyo mayumi megu megumi mi michi michiko midori mieko miho mika miki minako minori misaki mitsuko mitsuru miwa miyako miyoko miyuki mizuki moe momo momoe momoko moriko nana nanae nao naoki naoko naomi natsuko natsumi nobuko nori noriko ran rei reiko ren rie rika riko rin ryo ryoko sachiko saki sakiko sakura sango satoko sayuri setsuko shigeko shika shinju shiori shizuka shizuko sora sumiko susumu suzu suzume takako takara tamiko teruko tomiko tomoko toshiko tsukiko ukie ume umeko usagi yasu yasuko yoko yori yoshi yoshie yoshiko yuka yukako yuki yukie yukiko yuko yumi yumiko yuri yurie yuriko]

adj = %w[abundant adorable adventurous aggressive agreeable alert alive amused ancient angry annoyed annoying anxious arrogant ashamed attractive average awful bad beautiful better bewildered big bitter black bloody blue blushing boiling bored brainy brave breakable breezy brief bright broad broken bumpy busy calm careful cautious charming cheerful chilly chubby clean clear clever cloudy clumsy cold colorful colossal combative comfortable concerned condemned confused cooing cool cooperative courageous crazy creepy crooked crowded cruel cuddly curious curly curved cute damaged damp dangerous dark dead deafening deep defeated defiant delicious delightful depressed determined different difficult dirty disgusted distinct disturbed dizzy doubtful drab dry dull dusty eager easy elated elegant embarrassed empty enchanting encouraging energetic enthusiastic envious evil excited expensive exuberant faint fair faithful famous fancy fantastic fast fat few fierce filthy fine flaky flat fluffy fluttering foolish fragile frail frantic freezing fresh friendly frightened funny fuzzy gentle gifted gigantic glamorous gleaming glorious good gorgeous graceful greasy great grieving grotesque grubby grumpy handsome happy hard harsh healthy heavy helpful helpless high hilarious hissing hollow homeless homely horrible hot huge hungry hurt hushed husky icy ill immense important impossible inexpensive innocent inquisitive itchy jealous jittery jolly joyous juicy kind large late lazy light little lively lonely long loose loud lovely low lucky magnificent mammoth many massive melodic melted miniature misty moaning modern motionless muddy mushy mute mysterious narrow nasty naughty nervous nice noisy numerous nutritious nutty obedient obnoxious odd old open outrageous outstanding panicky perfect petite plain plastic pleasant poised poor powerful precious prickly proud puny purring puzzled quaint quick quiet rainy rapid raspy real relieved repulsive resonant rich ripe rotten rough round salty scary scattered scrawny screeching selfish shaggy shaky shallow sharp shiny shivering short shrill shy silent silky silly skinny sleepy slimy slippery slow small smiling smoggy smooth soft solid sore sour sparkling spicy splendid spotless square squealing stale steady steep sticky stormy straight strange strong stupid substantial successful super sweet swift talented tall tame tart tasteless tasty teeny tender tense terrible testy thankful thirsty thoughtful thoughtless thundering tight tiny tired tough troubled ugliest ugly uneven uninterested unsightly unusual upset uptight vast victorious vivacious voiceless wandering warm weak weary wet wet whispering wicked wide wide-eyed wild witty wonderful wooden worried wrong young yummy zany zealous]

flag = flag.slice(0,1)
if "m" == flag
  puts "#{adj.choice}#{glue}#{males.choice}"
elsif "f" == flag
  puts "#{adj.choice}#{glue}#{females.choice}"
else
  names = males.concat(females)
  puts "#{adj.choice}#{glue}#{names.choice}"
end

